### ISSUE TITLE
Controller not working after update to Lakka 3.4

### ISSUE THREAD

**Issue by ruiner9** [duduke/piboy-dmg-lakka-test#1]
After internal update to Lakka 3.4 and replacement of distroconfig.txt to enable the display DMG controller was undetected and non-functional. Followed step 13 to recreate the PiBoy DMG Controller.cfg file, and while PuTTY did not throw any errors, controller was still undetected. Keyboard still works to navigate the menus.

**Comment by justinthegeek** [comment]
`Lakka:~/roms/piboy-dmg # ./piboy-dmg-control.sh
insmod: ERROR: could not insert module /storage/roms/piboy-dmg/xpi_gamecon.ko: Invalid module format
cat: can't open '/sys/kernel/xpi_gamecon/volume': No such file or directory
cat: can't open '/sys/kernel/xpi_gamecon/status': No such file or directory
cat: can't open '/sys/kernel/xpi_gamecon/percent': No such file or directory
./piboy-dmg-control.sh: line 15: can't create /sys/kernel/xpi_gamecon/fan: nonexistent directory
bash: 6: unknown operand
bash: 5: unknown operand`

Looks like the kernel module might need to be rebuilt? If I get it working I'll throw in a PR.

**Comment by duduke** [comment]
Correct, 3.4 has a different kernel. But, Piboy DMG is already in the nightly builds of LAKKA. It mostly works, you can get it from there.
http://nightly.builds.lakka.tv/2021-09-11/RPi4-PiBoyDmg.aarch64/
